package Exception_handling;

public class Arithmetic_Exception {
public static void main(String[] args) {
	int a=10;
	int b=0;
try {
int c=a/b;
	}
catch(ArithmeticException e) {
	System.out.println("Boss expansion  is handled successfully");
}

}

}
